# Generated by Django 4.2.5 on 2023-09-15 05:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='time_added',
        ),
        migrations.AddField(
            model_name='person',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
