# Generated by Django 4.2.5 on 2023-09-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_remove_person_time_added_person_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
