# Generated by Django 4.2.5 on 2023-09-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_person_country_person_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
    ]
